RT-75: переписал бак на чистую архитектуру
go-park-mail-ru/2021_1_RedTech pull request #28
Opened 2021-03-22 12:29 UTC by paulnopaul

Я не учел обработку ошибок и mock-и. Мне кажется, их лучше в отдельные таски вынести, эта и так здоровенная какая-то получилась.

2021-03-22 16:38 UTC, K1ola requested changes
уф жесть (👏👍), в целом ты справился, но тут прям немного доделать. И вопрос с тестами еще открыт)

2021-03-22 16:38 UTC, K1ola commented on internal/app/server/runserver.go
> +	s.Use(middL.LoggingMiddleware)
логгер перестал почему-то логировать

2021-03-22 16:38 UTC, K1ola commented on internal/pkg/domain/movie.go
> +}
оффтоп: а остался fill() на тестовый список фильмов?

2021-03-22 16:38 UTC, K1ola commented on internal/pkg/user/delivery/http/avatar.go
> +	filename := RandString(32) + filepath.Ext(header.Filename)
определение RandString я бы в utils унесла

2021-03-22 16:38 UTC, K1ola commented on internal/pkg/user/delivery/http/avatar.go
>  	file, err := createFile(path, filename)
определение createFile я бы в utils унесла

2021-03-22 16:38 UTC, K1ola commented on internal/pkg/user/delivery/http/auth.go
> +		http.Error(w, `{"error":"Empty fields in form"}`, http.StatusBadRequest)
думаю, валидацию надо в useCase

2021-03-22 16:38 UTC, K1ola commented on internal/pkg/user/delivery/http/avatar.go
> +func (handler *UserHandler) Avatar(w http.ResponseWriter, r *http.Request) {
в целом по этой функции Avatar - она слишком привязана к сохранению в файл и слишком обширная для delivery. Если захотим переехать на какое нибудь облачное хранилище - придется переписывать код. Думаю, на апдейт аватара нужен отдельный useCase

2021-03-22 16:38 UTC, K1ola commented on internal/app/server/runserver.go
> +	r.PathPrefix("/static/users/").Handler(http.StripPrefix("/static/", static))
Получится вынести это аналогично _userHandler.NewUserHandlers(s, userUsecase) ? (может как часть NewUserHandlers)
Вешанье обработчиков на файл сервер получилось тут слишком обособлено от ручек на юзера

2021-03-22 17:11 UTC, paulnopaul commented on internal/app/server/runserver.go
> +	s.Use(middL.LoggingMiddleware)
Хм, у меня логирует 
![image](https://user-images.githubusercontent.com/33177954/112029932-c9896e80-8b4a-11eb-8ff2-2d3fecb69f2d.png)

2021-03-23 17:35 UTC, K1ola commented on internal/pkg/user/delivery/http/avatar.go
> +}
эту функцию лучше к RandString

2021-03-23 17:35 UTC, K1ola commented on internal/pkg/utils/fileutils/uploadfile.go
> +	log.Print("avatar name ", filename)
Если это нужный лог, давай его поинформативнее и покрасивее оформим

2021-03-23 17:35 UTC, K1ola commented on internal/pkg/utils/fileutils/uploadfile.go
> +	log.Print("avatar name ", filename)
Если это нужный лог, давай его поинформативнее и покрасивее оформим

2021-03-23 17:35 UTC, K1ola commented on internal/pkg/utils/fileutils/uploadfile.go
> +		log.Printf("Error while uploading file: %s", err)
Тут и далее: логировать ошибку лучше на самом верху стека вызова, иначе будут дублирующие друг друга логи. Ты уже обернул ошибку полезной нагрузкой с  `fmt.Errorf`, поэтому `log.Printf` можно убрать

2021-03-23 17:35 UTC, K1ola commented on internal/pkg/user/usecase/usecase.go
> +	panic("implement me")
implement it)))

2021-03-23 19:37 UTC, K1ola approved these changes

2021-03-24 06:30 UTC, merged