RT-35: начальный веб-сервер
go-park-mail-ru/2021_1_RedTech pull request #5
Opened 2021-03-06 13:36 UTC by paulnopaul

2021-03-06 18:57 UTC, K1ola requested changes

2021-03-06 18:57 UTC, K1ola commented on cmd/main.go
> +*/
Давай уберем эти комменты

2021-03-06 18:57 UTC, K1ola commented on go.sum
> +github.com/gorilla/mux v1.8.0 h1:i40aqfkR1h2SlN9hojwV5ZA91wcXFOvkdNIeFDP5koI=
добавь go.sum в .gitignore

2021-03-06 18:57 UTC, K1ola commented on internal/app/runserver.go
> +// (будет неясно как - пиши)
вот эти комменты давай тоже уберем)

2021-03-07 09:19 UTC, K1ola approved these changes

2021-03-07 10:04 UTC, paulnopaul commented on internal/app/runserver.go
> +// (будет неясно как - пиши)
Ой)

2021-03-07 10:10 UTC, paulnopaul commented
Убрал комментарии и добавил go.sum в .gitignore

2021-03-07 10:10 UTC, merged