RT-167: Отправка сообщений "Посмотреть позже"
go-park-mail-ru/2021_1_RedTech pull request #67
Opened 2021-05-20 13:49 UTC by timoninas

2021-05-20 22:26 UTC, K1ola requested changes
Не без моих локал фиксов, но письмо пришло (ура!), но давай оформим как-то нормально-продуктово (напр. "вы хотели посмотреть следующие фильмы" и ненумерованный оформленный список) + не через text/plain, а через text/html (можно шаблоном составить текст сообщения, можно просто строкой)
![image](https://user-images.githubusercontent.com/33131488/119056062-b96aff80-b9d2-11eb-9e86-36c93e3f11f9.png)

2021-05-20 22:26 UTC, K1ola commented on scripts/email_watchlist/main.go
> +	}
это наверное нужно убрать

2021-05-20 22:26 UTC, K1ola commented on internal/pkg/movie/delivery/http/handler.go
> +	router.HandleFunc("/media/movie/{id:[0-9]+}/watchlist", handler.SetWatchlist).Methods("POST", "OPTIONS")
это скорее всего GET, а не POST. Тебе в теле ничего не передается

2021-05-20 22:26 UTC, K1ola commented on internal/pkg/movie/delivery/http/watchlist.go
> +	case "delete":
это нужно в константы

2021-05-20 22:26 UTC, K1ola commented on internal/pkg/movie/delivery/http/watchlist.go
> +		http.Error(w, jsonerrors.URLParams, movie.CodeFromError(err))
jsonerrors.URLParams - захардкоженная ошибка. У тебя в err вся полезная инфа - ее и надо отдавать

2021-05-20 22:26 UTC, K1ola commented on internal/pkg/movie/repository/db_watchlist.go
> +	querySelectWatchlist = `select id from user_watchlist here user_id = $1 and movie_id = $2;`
очепятка в "here"

2021-05-20 22:26 UTC, K1ola commented on scripts/email_watchlist/main.go
> +}
Если я не ошибаюсь, задание было "напоминания по почте раз в n дней посмотреть что-то из списка "посмотреть позже"". То есть мы должны сделать рассылку не по всем юзерам, а только по тем, кто есть в таблице user_watchlist .

2021-05-20 22:26 UTC, K1ola commented on scripts/email_watchlist/main.go
> +}
Причем по коду в функции SendWatchlists в цикле по юзерам непонятно что происходит в логах - то успех, то эррор на пустой watchlist
![image](https://user-images.githubusercontent.com/33131488/119055606-01d5ed80-b9d2-11eb-9338-5a1f932595c3.png)

я уже молчу про дудос

2021-05-20 22:28 UTC, K1ola commented
Я надеялась на вариант реализации с горутиной, но такое решение имеет место быть, только если файлик `run_email_watchlist.sh` будет запускаться в кроне

2021-05-23 21:07 UTC, DmitryDorofeev commented on internal/pkg/movie/delivery/http/handler.go
> +	router.HandleFunc("/media/movie/{id:[0-9]+}/watchlist", handler.SetWatchlist).Methods("POST", "OPTIONS")
это точно не GET, так как меняет состояние сервера

2021-05-23 21:08 UTC, DmitryDorofeev commented on internal/pkg/movie/delivery/http/handler.go
> +	router.HandleFunc("/media/movie/{id:[0-9]+}/watchlist", handler.SetWatchlist).Methods("POST", "OPTIONS")
если это просто меняет список, то тут скорее PUT, потому что запрос будет идемпотентный

2021-05-23 21:10 UTC, DmitryDorofeev commented on internal/pkg/movie/delivery/http/watchlist.go
> +	case "delete":
а еще можно для DELETE сделать отдельный хендлер

2021-05-23 21:12 UTC, DmitryDorofeev commented on scripts/email_watchlist/main.go
> +	from := "redioteka@internet.ru"
это всё должно быть в конфиге

2021-05-23 21:12 UTC, DmitryDorofeev commented on scripts/email_watchlist/main.go
> +	d := gomail.NewDialer("smtp.mail.ru", 587, "redioteka@internet.ru", "CoolRedTech")
в конфиг

2021-05-23 21:13 UTC, DmitryDorofeev commented on scripts/email_watchlist/main.go
> +	users = []domain.User{
что за хардкод?

2021-05-30 13:09 UTC, closed without merging